// <auto-generated />
using System;
using CimtasHrPanel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CimtasHrPanel.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20250806111347_seeddata")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CimtasHrPanel.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "Pazarlama"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "İnsan kaynakları"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Üretim"
                        });
                });

            modelBuilder.Entity("CimtasHrPanel.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LeaveTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("PersonId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("CimtasHrPanel.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsIncreaseAnnualValue")
                        .HasColumnType("bit");

                    b.Property<string>("LeaveTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsIncreaseAnnualValue = true,
                            LeaveTypeName = "Yıllık İzin"
                        },
                        new
                        {
                            Id = 2,
                            IsIncreaseAnnualValue = false,
                            LeaveTypeName = "Hastalık İzni"
                        },
                        new
                        {
                            Id = 3,
                            IsIncreaseAnnualValue = false,
                            LeaveTypeName = "Ücretsiz İzin"
                        });
                });

            modelBuilder.Entity("CimtasHrPanel.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("PersonLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            PersonLastName = "Yılmaz",
                            PersonName = "Ahmet"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            PersonLastName = "Soy",
                            PersonName = "Büşra"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            PersonLastName = "Ay",
                            PersonName = "Kadir"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 3,
                            PersonLastName = "Yılmaz",
                            PersonName = "Mehmet"
                        });
                });

            modelBuilder.Entity("CimtasHrPanel.Models.LeaveRequest", b =>
                {
                    b.HasOne("CimtasHrPanel.Models.Department", null)
                        .WithMany("LeaveRequests")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("CimtasHrPanel.Models.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CimtasHrPanel.Models.Person", "Person")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("CimtasHrPanel.Models.Person", b =>
                {
                    b.HasOne("CimtasHrPanel.Models.Department", "Department")
                        .WithMany("Persons")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CimtasHrPanel.Models.Department", b =>
                {
                    b.Navigation("LeaveRequests");

                    b.Navigation("Persons");
                });

            modelBuilder.Entity("CimtasHrPanel.Models.Person", b =>
                {
                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
